### ISSUE TITLE
CTK-551 not appearing in the MIDI setup

### ISSUE THREAD

**Issue by BeezWaxandnectar** [francoisferland/casiousbmididriver#47]
Hi, I installed the driver into the MIDI drivers folder, restarted, and it wasn't in the MIDI setup when I opened it back up. I think the computer is registering it as an after-effects plugin because of the file type? I'm not sure to be honest.

I'm using OSX 11.3.1, and the keyboard is a CTK-551 from my grandma. As far as I know it's still working properly. Any help would be appreciated!

**Comment by francoisferland** [comment]
Hi, can you tell me in which folder exactly ? /Library/Audio/MIDI Drivers or /Users/(your name)/Library/Audio/MIDI Drivers ?

**Comment by francoisferland** [comment]
Hi again, I have another question : How do you connect the keyboard to your computer ? I did a quick search and I cannot confirm if the CTK-551 has a USB port or not. This driver is only for Casio keyboards with a USB-A port.

**Comment by BeezWaxandnectar** [comment]
Hello, for the first question I put it in /Users/myname/Library/Audio/MIDI Drivers

And for the second question, the CTK-551 has no USB port on it, I'm using a midi to USB-C adaptor.  Is that not going to work?

**Comment by francoisferland** [comment]
Hello again, you will need to check with the manufacturer of the USB-C to MIDI port, because this driver will not help unfortunately. However, if it's a recent adapter, it should work "out of the box". You will not see a device named "CASIO", but you should see something that corresponds to the USB-C adapter. Then your keyboard should work in any MIDI-compatible software, as long as you choose the USB-C adapter as input.

**Comment by BeezWaxandnectar** [comment]
Ok, thanks for letting me know!
